import sqlite3

båsliste = [
    {"AfstandFI": 54, "BLokationKode": "A1", "Ledig": 1, "Type": "handicap"},
    {"AfstandFI": 57, "BLokationKode": "A2", "Ledig": 1, "Type": "handicap"},
    {"AfstandFI": 60, "BLokationKode": "A3", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 62, "BLokationKode": "A4", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 67, "BLokationKode": "A5", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 69, "BLokationKode": "A6", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 72, "BLokationKode": "A7", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 74, "BLokationKode": "A8", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 77, "BLokationKode": "A9", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 67, "BLokationKode": "B1", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 69, "BLokationKode": "B2", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 71, "BLokationKode": "B3", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 73, "BLokationKode": "B4", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 80, "BLokationKode": "B5", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 82, "BLokationKode": "B6", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 85, "BLokationKode": "B7", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 87, "BLokationKode": "B8", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 90, "BLokationKode": "B9", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 71, "BLokationKode": "C1", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 74, "BLokationKode": "C2", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 76, "BLokationKode": "C3", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 78, "BLokationKode": "C4", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 83, "BLokationKode": "C5", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 85, "BLokationKode": "C6", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 87, "BLokationKode": "C7", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 90, "BLokationKode": "C8", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 92, "BLokationKode": "C9", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 82, "BLokationKode": "D1", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 84, "BLokationKode": "D2", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 86, "BLokationKode": "D3", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 89, "BLokationKode": "D4", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 91, "BLokationKode": "D5", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 93, "BLokationKode": "D6", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 95, "BLokationKode": "D7", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 97, "BLokationKode": "D8", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 100, "BLokationKode": "D9", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 105, "BLokationKode": "D10", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 108, "BLokationKode": "D11", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 88, "BLokationKode": "E1", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 91, "BLokationKode": "E2", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 93, "BLokationKode": "E3", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 96, "BLokationKode": "E4", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 99, "BLokationKode": "E5", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 102, "BLokationKode": "E6", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 105, "BLokationKode": "E7", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 110, "BLokationKode": "E8", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 113, "BLokationKode": "E9", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 116, "BLokationKode": "E10", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 118, "BLokationKode": "E11", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 95, "BLokationKode": "F1", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 97, "BLokationKode": "F2", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 102, "BLokationKode": "F3", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 105, "BLokationKode": "F4", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 108, "BLokationKode": "F5", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 110, "BLokationKode": "F6", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 113, "BLokationKode": "F7", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 115, "BLokationKode": "F8", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 118, "BLokationKode": "F9", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 120, "BLokationKode": "F10", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 123, "BLokationKode": "F11", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 103, "BLokationKode": "G1", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 105, "BLokationKode": "G2", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 110, "BLokationKode": "G3", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 113, "BLokationKode": "G4", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 116, "BLokationKode": "G5", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 118, "BLokationKode": "G6", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 121, "BLokationKode": "G7", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 123, "BLokationKode": "G8", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 126, "BLokationKode": "G9", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 128, "BLokationKode": "G10", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 130, "BLokationKode": "G11", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 116, "BLokationKode": "H1", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 119, "BLokationKode": "H2", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 121, "BLokationKode": "H3", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 123, "BLokationKode": "H4", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 125, "BLokationKode": "H5", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 128, "BLokationKode": "H6", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 131, "BLokationKode": "H7", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 137, "BLokationKode": "H8", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 139, "BLokationKode": "H9", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 141, "BLokationKode": "H10", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 144, "BLokationKode": "H11", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 59, "BLokationKode": "I1", "Ledig": 1, "Type": "handicap"},
    {"AfstandFI": 66, "BLokationKode": "I2", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 68, "BLokationKode": "I3", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 70, "BLokationKode": "I4", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 73, "BLokationKode": "I5", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 64, "BLokationKode": "J1", "Ledig": 1, "Type": "handicap"},
    {"AfstandFI": 71, "BLokationKode": "J2", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 73, "BLokationKode": "J3", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 75, "BLokationKode": "J4", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 77, "BLokationKode": "J5", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 79, "BLokationKode": "J6", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 82, "BLokationKode": "J7", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 84, "BLokationKode": "J8", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 75, "BLokationKode": "K1", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 78, "BLokationKode": "K2", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 80, "BLokationKode": "K3", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 82, "BLokationKode": "K4", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 85, "BLokationKode": "K5", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 88, "BLokationKode": "K6", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 90, "BLokationKode": "K7", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 93, "BLokationKode": "K8", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 95, "BLokationKode": "K9", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 98, "BLokationKode": "K10", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 102, "BLokationKode": "K11", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 105, "BLokationKode": "K12", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 107, "BLokationKode": "K13", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 109, "BLokationKode": "K14", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 111, "BLokationKode": "K15", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 80, "BLokationKode": "L1", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 82, "BLokationKode": "L2", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 84, "BLokationKode": "L3", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 87, "BLokationKode": "L4", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 89, "BLokationKode": "L5", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 91, "BLokationKode": "L6", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 94, "BLokationKode": "L7", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 96, "BLokationKode": "L8", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 98, "BLokationKode": "L9", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 101, "BLokationKode": "L10", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 107, "BLokationKode": "L11", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 109, "BLokationKode": "L12", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 111, "BLokationKode": "L13", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 114, "BLokationKode": "L14", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 96, "BLokationKode": "M1", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 98, "BLokationKode": "M2", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 101, "BLokationKode": "M3", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 103, "BLokationKode": "M4", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 106, "BLokationKode": "M5", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 109, "BLokationKode": "M6", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 111, "BLokationKode": "M7", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 113, "BLokationKode": "M8", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 116, "BLokationKode": "M9", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 119, "BLokationKode": "M10", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 121, "BLokationKode": "M11", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 124, "BLokationKode": "M12", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 127, "BLokationKode": "M13", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 129, "BLokationKode": "M14", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 131, "BLokationKode": "M15", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 137, "BLokationKode": "M16", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 101, "BLokationKode": "N1", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 104, "BLokationKode": "N2", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 106, "BLokationKode": "N3", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 108, "BLokationKode": "N4", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 110, "BLokationKode": "N5", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 112, "BLokationKode": "N6", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 115, "BLokationKode": "N7", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 117, "BLokationKode": "N8", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 119, "BLokationKode": "N9", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 122, "BLokationKode": "N10", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 125, "BLokationKode": "N11", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 128, "BLokationKode": "N12", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 130, "BLokationKode": "N13", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 133, "BLokationKode": "N14", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 136, "BLokationKode": "N15", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 142, "BLokationKode": "N16", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 109, "BLokationKode": "O1", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 112, "BLokationKode": "O2", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 118, "BLokationKode": "O3", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 120, "BLokationKode": "O4", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 123, "BLokationKode": "O5", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 125, "BLokationKode": "O6", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 128, "BLokationKode": "O7", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 130, "BLokationKode": "O8", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 132, "BLokationKode": "O9", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 135, "BLokationKode": "O10", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 140, "BLokationKode": "O11", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 143, "BLokationKode": "O12", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 145, "BLokationKode": "O13", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 147, "BLokationKode": "O14", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 115, "BLokationKode": "P1", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 118, "BLokationKode": "P2", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 124, "BLokationKode": "P3", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 126, "BLokationKode": "P4", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 128, "BLokationKode": "P5", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 131, "BLokationKode": "P6", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 134, "BLokationKode": "P7", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 137, "BLokationKode": "P8", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 140, "BLokationKode": "P9", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 142, "BLokationKode": "P10", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 147, "BLokationKode": "P11", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 149, "BLokationKode": "P12", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 151, "BLokationKode": "P13", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 154, "BLokationKode": "P14", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 126, "BLokationKode": "Q1", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 128, "BLokationKode": "Q2", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 131, "BLokationKode": "Q3", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 134, "BLokationKode": "Q4", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 136, "BLokationKode": "Q5", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 139, "BLokationKode": "Q6", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 141, "BLokationKode": "Q7", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 144, "BLokationKode": "Q8", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 146, "BLokationKode": "Q9", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 148, "BLokationKode": "Q10", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 150, "BLokationKode": "Q11", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 152, "BLokationKode": "Q12", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 155, "BLokationKode": "Q13", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 157, "BLokationKode": "Q14", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 159, "BLokationKode": "Q15", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 161, "BLokationKode": "Q16", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 163, "BLokationKode": "Q17", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 165, "BLokationKode": "Q18", "Ledig": 1, "Type": "almindelig"},
]


def get_db_connection():
    conn = sqlite3.connect("Stefan/ParkeringsDatabase.db")
    conn.row_factory = sqlite3.Row
    return conn

def init_db():
    conn= get_db_connection()
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS ParkeringsDatabase (
        AfstandFI INTEGER NOT NULL,
        BLokationKode TEXT PRIMARY KEY NOT NULL UNIQUE,
        Ledig INTEGER NOT NULL,
        Type TEXT NOT NULL
        );
        """
    )
    conn.commit()
    if conn.execute("SELECT COUNT(*) FROM ParkeringsDatabase").fetchall()[0][0] == 0:
        for bås in båsliste:
            conn.execute(
                f"""
                INSERT INTO ParkeringsDatabase (AfstandFI, BLokationKode, Ledig, Type) 
                VAlUES ({bås['AfstandFI']},"{bås['BLokationKode']}",{bås['Ledig']},"{bås['Type']}");
                """
            )
            conn.commit() 
    conn.close()
init_db()
