import sqlite3

båsliste = [
    {"AfstandFI": 10, "BLokationKode": "A1", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "A2", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "A3", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "A4", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "A5", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "A6", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "A7", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "A8", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "A9", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "A10", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "A11", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "A12", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "A13", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "A14", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "A15", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "A16", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "A17", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "B1", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "B2", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "B3", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "B4", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "B5", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "B6", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "B7", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "B8", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "B9", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "B10", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "B11", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "B12", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "B13", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "B14", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "B15", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "B16", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "B17", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "C1", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "C2", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "C3", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "C4", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "C5", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "C6", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "C7", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "C8", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "C9", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "C10", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "C11", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "C12", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "C13", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "C14", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "C15", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "C16", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "C17", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "D1", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "D2", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "D3", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "D4", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "D5", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "D6", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "D7", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "D8", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "D9", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "D10", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "D11", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "D12", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "D13", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "D14", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "D15", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "D16", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "D17", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "E1", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "E2", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "E3", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "E4", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "E5", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "E6", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "E7", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "E8", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "E9", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "E10", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "E11", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "E12", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "E13", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "E14", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "E15", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "E16", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "E17", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "F1", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "F2", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "F3", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "F4", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "F5", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "F6", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "F7", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "F8", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "F9", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "F10", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "F11", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "F12", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "F13", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "F14", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "F15", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "F16", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "F17", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "G1", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "G2", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "G3", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "G4", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "G5", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "G6", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "G7", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "G8", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "G9", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "G10", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "G11", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "G12", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "G13", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "G14", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "G15", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "G16", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "G17", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "H1", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "H2", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "H3", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "H4", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "H5", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "H6", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "H7", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "H8", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "H9", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "H10", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "H11", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "H12", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "H13", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "H14", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "H15", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "H16", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "H17", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "I1", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "I2", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "I3", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "I4", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "I5", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "I6", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "I7", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "I8", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "I9", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "I10", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "I11", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "I12", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "I13", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "I14", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "I15", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "I16", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "I17", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "J1", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "J2", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "J3", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "J4", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "J5", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "J6", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "J7", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "J8", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "J9", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "J10", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "J11", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "J12", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "J13", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "J14", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "J15", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "J16", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "J17", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "K1", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "K2", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "K3", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "K4", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "K5", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "K6", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "K7", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "K8", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "K9", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "K10", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "K11", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "K12", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "K13", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "K14", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "K15", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "K16", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "K17", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "L1", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "L2", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "L3", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "L4", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "L5", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "L6", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "L7", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "L8", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "L9", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "L10", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "L11", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "L12", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "L13", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "L14", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "L15", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "L16", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "L17", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "M1", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "M2", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "M3", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "M4", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "M5", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "M6", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "M7", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "M8", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "M9", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "M10", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "M11", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "M12", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "M13", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "M14", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "M15", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "M16", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "M17", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "N1", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "N2", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "N3", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "N4", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "N5", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "N6", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "N7", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "N8", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "N9", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "N10", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "N11", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "N12", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "N13", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "N14", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "N15", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "N16", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "N17", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "O1", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "O2", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "O3", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "O4", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "O5", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "O6", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "O7", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "O8", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "O9", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "O10", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "O11", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "O12", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "O13", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "O14", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "O15", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "O16", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "O17", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "P1", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "P2", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "P3", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "P4", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "P5", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "P6", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "P7", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "P8", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "P9", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "P10", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "P11", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "P12", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "P13", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "P14", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "P15", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "P16", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "P17", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "Q1", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "Q2", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "Q3", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "Q4", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "Q5", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "Q6", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "Q7", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "Q8", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "Q9", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "Q10", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "Q11", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "Q12", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "Q13", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "Q14", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "Q15", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "Q16", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "Q17", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "R1", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "R2", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "R3", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "R4", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "R5", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "R6", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "R7", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "R8", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "R9", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "R10", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "R11", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "R12", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "R13", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "R14", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "R15", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "R16", "Ledig": 1, "Type": "almindelig"},
    {"AfstandFI": 10, "BLokationKode": "R17", "Ledig": 1, "Type": "almindelig"},
]





def get_db_connection():
    conn = sqlite3.connect("Stefan/ParkeringsDatabase.db")
    conn.row_factory = sqlite3.Row
    return conn

def init_db():
    conn= get_db_connection()
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS ParkeringsDatabase (
        AfstandFI INTEGER NOT NULL,
        BLokationKode TEXT PRIMARY KEY NOT NULL UNIQUE,
        Ledig INTEGER NOT NULL,
        Type TEXT NOT NULL
        );
        """
    )
    conn.commit()
    if conn.execute("SELECT COUNT(*) FROM parkerings_system").fetchall()[0][0] == 0:
        for bås in båsliste:
            conn.execute(
                """
                INSERT INTO parkerings_system (AfstandFI, BLokationKode, Ledig, Type) 
                VAlUES ("""+{bås["AfstandFI"]}+"""), '"""+{bås["BLokationKode"]}+"""', """+{bås["Ledig"]}+""", '"""+{bås["Type"]}+"""');
                """
            )
            conn.commit() 
    conn.close()

